### ISSUE TITLE
BGS overwhelmed notification

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#116]
**Is your feature request related to a problem? Please describe.**
When the tracker does not track an object, it would be good to know if this is because its currently overwhelmed and needs a mask applied.

**Describe the solution you'd like**
Some sort of console write to indicate that the BGS is overwhelmed would be great.

**Describe alternatives you've considered**
Being able to see the BGS Foreground mask would also help make this determination.

**Additional context**
We were testing a drone flying over the house, it did not track and we were not sure if this was due to it not being detected or the BGS being overwhelmed.

**Comment by jdmaudio** [comment]
"BGS overwhelmed" should actually be BlobDetector overwhelmed I think.

Currently we set a max number of blobs in app_config to e.g. 50. However, if we get a lot activity in the BGS foreground mask we can hit that limit and when it does, our Blob Detector no longer supplies any bounding boxes to SORT.

My proposal is to update the 'detect' function in ConnectedBlobDetection class in Boblib so that it better indicates if the max blobs limit has been reached or not e.g. return a DetectionStatus rather than a bool

enum class DetectionStatus
{
Success,
MaxBlobsReached,
NoBlobsDetected
};

This would give us the basis to supply e.g. a console message from the ros calling node What do you think @fcbarros ?

**Comment by Micky-G** [comment]
I think this suggestion would be really cool as we can then drive changes to the system given the fact that the blob detector is getting overwhelmed like, automatically lowering the sensitivity or requesting a mask if one is not applied etc.

**Comment by Micky-G** [comment]
This should be fixed in the PR mentioned above.
