### ISSUE TITLE
Define the conditions required to record a track

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#54]

**Comment by fcbarros** [comment]
I was thinking:
* separating videos in folders by duration, for instance, folder for less than 5 seconds and the rest, this way we don't miss fast moving objects
* start recording a few seconds before and after

**Comment by jdmaudio** [comment]
Pre and post capture is really important I think because sometimes it could take e.g. tracker a little time to lock onto an object. And e.g. an occlusion could be what determines the end of the recording.

Might also be worth considering having a maximum record time and event record gap as safe guards?

**Comment by Micky-G** [comment]
Agreed on 2023.10.14 that we can close this issue for now
